# Generated by Django 3.1.4 on 2022-09-15 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='компании')),
            ],
        ),
        migrations.RemoveField(
            model_name='lead',
            name='Company',
        ),
        migrations.AddField(
            model_name='lead',
            name='Company',
            field=models.ManyToManyField(null=True, to='leads.Company', verbose_name='Компания'),
        ),
    ]
