# Generated by Django 3.1.4 on 2022-09-23 10:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Apparats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='модель')),
            ],
        ),
        migrations.CreateModel(
            name='Number',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Номер телефона 2')),
            ],
        ),
        migrations.AlterField(
            model_name='lead',
            name='Company',
            field=models.ManyToManyField(to='leads.Company', verbose_name='Компания'),
        ),
        migrations.RemoveField(
            model_name='lead',
            name='phone_model',
        ),
        migrations.AddField(
            model_name='lead',
            name='phone_model',
            field=models.ManyToManyField(to='leads.Apparats', verbose_name='Модель телефона'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='phone_number',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='leads.number', verbose_name='Номер телефона'),
        ),
    ]
