# Generated by Django 3.2 on 2022-10-31 07:15

from django.db import migrations, models
import django_extensions.db.fields
import shortuuid.main


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='mac_address',
            field=models.CharField(blank=True, max_length=17, verbose_name='MAC-Адрес'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='passwd',
            field=django_extensions.db.fields.ShortUUIDField(blank=True, default=shortuuid.main.ShortUUID.uuid, editable=False, unique=True, verbose_name='Пароль'),
        ),
    ]
