# Generated by Django 3.1.4 on 2022-10-02 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='organisation',
        ),
        migrations.RemoveField(
            model_name='followup',
            name='lead',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='age',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='agent',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='category',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='converted_date',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='description',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='email',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='organisation',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='profile_picture',
        ),
        migrations.DeleteModel(
            name='Agent',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='FollowUp',
        ),
    ]
