# Generated by Django 3.2 on 2022-10-21 08:06

from django.db import migrations
import django.db.models.deletion
import django_extensions.db.fields
import shortuuid.main
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0002_auto_20221021_0758'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='passwd',
            field=django_extensions.db.fields.ShortUUIDField(blank=True, default=shortuuid.main.ShortUUID.uuid, editable=False, unique=True, verbose_name='Пароль'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='phone_number',
            field=smart_selects.db_fields.ChainedForeignKey(on_delete=django.db.models.deletion.PROTECT, to='leads.number', verbose_name='Номер телефона'),
        ),
    ]
