# Generated by Django 3.2 on 2022-10-21 11:08

from django.db import migrations
import django_extensions.db.fields
import shortuuid.main


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0002_auto_20221021_1053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='passwd',
            field=django_extensions.db.fields.ShortUUIDField(blank=True, default=shortuuid.main.ShortUUID.uuid, editable=False, unique=True, verbose_name='Пароль'),
        ),
    ]
