# Generated by Django 3.2 on 2022-12-07 08:10

from django.db import migrations, models
import django_extensions.db.fields
import shortuuid.main


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0005_auto_20221207_1430'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='created_user',
            field=models.CharField(blank=True, max_length=20, verbose_name='Создатель'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='passwd',
            field=django_extensions.db.fields.ShortUUIDField(blank=True, default=shortuuid.main.ShortUUID.uuid, editable=False, verbose_name='Пароль'),
        ),
    ]
