# Generated by Django 3.2 on 2025-04-20 06:50

import django.core.validators
from django.db import migrations, models
import django_extensions.db.fields
import shortuuid.main


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0006_auto_20221207_1610'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='call_forwarding',
            field=models.CharField(blank=True, max_length=11, null=True, validators=[django.core.validators.RegexValidator('^\\d{0,11}$', message='Поле должно содержать только цифры и быть не длиннее 11 символов.')], verbose_name='Переадресация'),
        ),
        migrations.AddField(
            model_name='lead',
            name='external_line_access',
            field=models.CharField(choices=[('локальные_МГ', 'Локальные МГ'), ('локальные_МГ_МН', 'Локальные МГ и МН'), ('локальные', 'Локальные')], default='локальные_МГ', max_length=20, verbose_name='Доступ к внешним линиям'),
        ),
        migrations.AddField(
            model_name='lead',
            name='record_calls',
            field=models.BooleanField(default=False, verbose_name='Запись разговоров'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='created_user',
            field=models.CharField(blank=True, max_length=20, verbose_name='Добавил'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='mac_address',
            field=models.CharField(blank=True, max_length=17, validators=[django.core.validators.MinLengthValidator(12)], verbose_name='MAC-Адрес'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='passwd',
            field=django_extensions.db.fields.ShortUUIDField(blank=True, default=shortuuid.main.ShortUUID.uuid, editable=False, verbose_name='Пароль'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='updated_user',
            field=models.CharField(blank=True, max_length=20, verbose_name='Обновил'),
        ),
    ]
