# Generated by Django 3.2 on 2025-04-28 15:30

from django.db import migrations, models
import django_extensions.db.fields
import shortuuid.main


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0007_auto_20250420_1450'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='timezone',
            field=models.CharField(choices=[('+8', 'Иркутск +8'), ('+3', 'Москва +3'), ('+7', 'Новосибирск +7'), ('+9', 'Якутск +9')], default='+8', max_length=3, verbose_name='Часовой пояс'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='passwd',
            field=django_extensions.db.fields.ShortUUIDField(blank=True, default=shortuuid.main.ShortUUID.uuid, editable=False, verbose_name='Пароль'),
        ),
    ]
