# Generated by Django 3.2 on 2026-02-08 09:51

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields
import shortuuid.main


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0009_alter_lead_passwd'),
    ]

    operations = [
        migrations.CreateModel(
            name='SyncSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interval_hours', models.PositiveIntegerField(default=24, verbose_name='Интервал синхронизации (часы)')),
                ('last_sync', models.DateTimeField(blank=True, null=True, verbose_name='Дата последней синхронизации')),
                ('night_only', models.BooleanField(default=True, verbose_name='Только ночью (00:00–06:00)')),
            ],
            options={
                'verbose_name': 'Настройки синхронизации',
                'verbose_name_plural': 'Настройки синхронизации',
            },
        ),
        migrations.AddField(
            model_name='lead',
            name='display_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='Отображаемое имя'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='passwd',
            field=django_extensions.db.fields.ShortUUIDField(blank=True, default=shortuuid.main.ShortUUID.uuid, editable=False, max_length=32, verbose_name='Пароль'),
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guid', models.CharField(max_length=36, unique=True, verbose_name='GUID_NSI')),
                ('full_name', models.CharField(max_length=150, verbose_name='ФИО полностью')),
                ('last_name', models.CharField(blank=True, max_length=50, verbose_name='Фамилия')),
                ('first_name', models.CharField(blank=True, max_length=50, verbose_name='Имя')),
                ('patronymic_name', models.CharField(blank=True, max_length=50, verbose_name='Отчество')),
                ('sam_account_name', models.CharField(blank=True, max_length=100, unique=True, verbose_name='Логин AD')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('department', models.CharField(blank=True, max_length=150, verbose_name='Подразделение')),
                ('job_title', models.CharField(blank=True, max_length=150, verbose_name='Должность')),
                ('active', models.BooleanField(default=True, verbose_name='Активен')),
                ('synced_at', models.DateTimeField(auto_now=True, verbose_name='Дата синхронизации')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='leads.company', verbose_name='Компания')),
            ],
            options={
                'verbose_name': 'Сотрудник (синхр. из AD)',
                'verbose_name_plural': 'Сотрудники (синхр. из AD)',
            },
        ),
        migrations.AddField(
            model_name='lead',
            name='employees',
            field=models.ManyToManyField(blank=True, to='leads.Employee', verbose_name='Привязанные сотрудники'),
        ),
    ]
