# Generated by Django 3.2 on 2026-02-08 13:38

from django.db import migrations, models
import django_extensions.db.fields
import shortuuid.main


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0009_alter_lead_passwd'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guid', models.CharField(db_index=True, max_length=64, unique=True, verbose_name='GUID')),
                ('full_name', models.CharField(blank=True, max_length=100, verbose_name='ФИО')),
                ('first_name', models.CharField(blank=True, max_length=50, verbose_name='Имя')),
                ('last_name', models.CharField(blank=True, max_length=50, verbose_name='Фамилия')),
                ('patronymic_name', models.CharField(blank=True, max_length=50, verbose_name='Отчество')),
                ('sam_account_name', models.CharField(blank=True, db_index=True, max_length=100, verbose_name='Логин AD')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('company_text', models.CharField(blank=True, max_length=255, verbose_name='Компания (из MSSQL текстом)')),
                ('department', models.CharField(blank=True, max_length=150, verbose_name='Подразделение')),
                ('job_title', models.CharField(blank=True, max_length=150, verbose_name='Должность')),
                ('sync_status', models.CharField(db_index=True, default='active', max_length=20, verbose_name='Статус')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата удаления')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SyncSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interval_hours', models.PositiveIntegerField(default=24, verbose_name='Интервал, часы')),
                ('night_only', models.BooleanField(default=True, verbose_name='Только ночью')),
                ('night_start_hour', models.PositiveIntegerField(default=0, verbose_name='Ночь старт (час)')),
                ('night_end_hour', models.PositiveIntegerField(default=6, verbose_name='Ночь конец (час)')),
                ('last_sync', models.DateTimeField(blank=True, null=True, verbose_name='Последняя синхронизация')),
            ],
        ),
        migrations.AlterField(
            model_name='lead',
            name='passwd',
            field=django_extensions.db.fields.ShortUUIDField(blank=True, default=shortuuid.main.ShortUUID.uuid, editable=False, max_length=32, verbose_name='Пароль'),
        ),
    ]
