# Generated by Django 3.2 on 2026-02-08 18:11

from django.db import migrations, models
import django_extensions.db.fields
import shortuuid.main


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0009_alter_lead_passwd'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeDwh',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guid_nsi', models.UUIDField(db_index=True, unique=True)),
                ('full_name', models.CharField(blank=True, max_length=255)),
                ('samaccountname', models.CharField(db_index=True, max_length=150)),
                ('mail', models.EmailField(blank=True, max_length=254)),
                ('company', models.CharField(blank=True, max_length=255)),
                ('department', models.CharField(blank=True, max_length=255)),
                ('job_title', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('active', 'Активен'), ('deleted', 'Удалён в источнике'), ('disabled', 'Отключён'), ('other', 'Другое')], db_index=True, default='active', max_length=20)),
                ('source_last_seen_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='lead',
            name='passwd',
            field=django_extensions.db.fields.ShortUUIDField(blank=True, default=shortuuid.main.ShortUUID.uuid, editable=False, max_length=32, verbose_name='Пароль'),
        ),
    ]
