# Generated by Django 3.2 on 2026-02-08 13:46

from django.db import migrations
import django_extensions.db.fields
import shortuuid.main


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0010_auto_20260208_2138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='passwd',
            field=django_extensions.db.fields.ShortUUIDField(blank=True, default=shortuuid.main.ShortUUID.uuid, editable=False, max_length=32, verbose_name='Пароль'),
        ),
    ]
