# Generated by Django 3.2 on 2026-02-08 18:32

from django.db import migrations, models
import django_extensions.db.fields
import shortuuid.main


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0010_auto_20260209_0211'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='employees',
            field=models.ManyToManyField(blank=True, related_name='leads', to='leads.EmployeeDwh', verbose_name='Сотрудники (DWH)'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='passwd',
            field=django_extensions.db.fields.ShortUUIDField(blank=True, default=shortuuid.main.ShortUUID.uuid, editable=False, max_length=32, verbose_name='Пароль'),
        ),
    ]
