# Generated by Django 3.2 on 2026-02-08 14:15

from django.db import migrations, models
import django_extensions.db.fields
import shortuuid.main


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0011_alter_lead_passwd'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='display_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Отображаемое имя'),
        ),
        migrations.AddField(
            model_name='lead',
            name='employees',
            field=models.ManyToManyField(blank=True, related_name='leads', to='leads.Employee', verbose_name='Сотрудники (синхронизация)'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='passwd',
            field=django_extensions.db.fields.ShortUUIDField(blank=True, default=shortuuid.main.ShortUUID.uuid, editable=False, max_length=32, verbose_name='Пароль'),
        ),
    ]
