# Generated by Django 3.2 on 2026-02-17 04:57

from django.db import migrations, models
import django_extensions.db.fields
import shortuuid.main


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0011_auto_20260209_0232'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='display_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Отображаемое имя'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='passwd',
            field=django_extensions.db.fields.ShortUUIDField(blank=True, default=shortuuid.main.ShortUUID.uuid, editable=False, max_length=32, verbose_name='Пароль'),
        ),
    ]
