# Generated by Django 3.2 on 2026-02-08 16:13

from django.db import migrations, models
import django_extensions.db.fields
import shortuuid.main


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0012_auto_20260208_2215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='first_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='last_name',
            field=models.CharField(max_length=100, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='passwd',
            field=django_extensions.db.fields.ShortUUIDField(blank=True, default=shortuuid.main.ShortUUID.uuid, editable=False, max_length=32, verbose_name='Пароль'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='patronymic_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Отчество'),
        ),
    ]
