# Generated by Django 3.2 on 2026-03-27 04:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields
import shortuuid.main


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0012_auto_20260217_1257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='passwd',
            field=django_extensions.db.fields.ShortUUIDField(blank=True, default=shortuuid.main.ShortUUID.uuid, editable=False, max_length=32, verbose_name='Пароль'),
        ),
        migrations.CreateModel(
            name='ApiToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название токена')),
                ('token', models.CharField(db_index=True, max_length=128, unique=True, verbose_name='Токен')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Кем создан')),
            ],
        ),
    ]
